name: Apollo Studio

on: [push]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: rover fetch
        uses: danielsinclair/rover-setup@v1
        with:
          args: graph publish Rossum@current --schema ../../schema.graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
